# -*- coding: utf-8 -*-
"""fetch_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQZ1Ux-9K38pr8NyWU2bRtiPZwy5ecPo
"""

# fetch_features.py
import os
import requests
import pandas as pd
from datetime import datetime

API_KEY = os.getenv('OPENWEATHER_API_KEY')
if not API_KEY:
    raise ValueError("OPENWEATHER_API_KEY environment variable is required")
LAT, LON = 24.8607, 67.0011  # Karachi

# --- Fetch weather data ---
weather_url = f"https://api.open-meteo.com/v1/forecast?latitude={LAT}&longitude={LON}&current_weather=true"
weather_data = requests.get(weather_url).json()
current_weather = weather_data["current_weather"]

temperature = current_weather["temperature"]
windspeed = current_weather["windspeed"]
winddirection = current_weather["winddirection"]
time_now = datetime.utcnow()

# --- Fetch pollutant data ---
pollution_url = f"http://api.openweathermap.org/data/2.5/air_pollution?lat={LAT}&lon={LON}&appid={API_KEY}"
pollution_data = requests.get(pollution_url).json()
pollutants = pollution_data["list"][0]["components"]

# --- Prepare row ---
row = {
    "datetime": time_now,
    "temperature_2m": temperature,
    "relative_humidity_2m": 50,  # If not available, use placeholder
    "windspeed_10m": windspeed,
    "winddirection_10m": winddirection,
    "precipitation": 0.0,
    "cloudcover": 50,
    "surface_pressure": 1000,
    "co": pollutants["co"],
    "no": pollutants["no"],
    "no2": pollutants["no2"],
    "o3": pollutants["o3"],
    "so2": pollutants["so2"],
    "pm2_5": pollutants["pm2_5"],
    "pm10": pollutants["pm10"],
    "nh3": pollutants["nh3"],
    "hour": time_now.hour,
    "day": time_now.day,
    "month": time_now.month
}

# --- Append to CSV ---
try:
    df = pd.read_csv("features.csv")
except FileNotFoundError:
    df = pd.DataFrame()

df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
df.drop_duplicates(subset=["datetime"], inplace=True)
df.to_csv("features.csv", index=False)

print("✅ New feature row added at", time_now)