# -*- coding: utf-8 -*-
"""fetch_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQZ1Ux-9K38pr8NyWU2bRtiPZwy5ecPo
"""

# fetch_features.py
import os
import pandas as pd
from datetime import datetime
import requests

API_KEY = os.environ.get("6ba231e87114c1df16cde745209442d4")
LAT, LON = 24.8607, 67.0011   # Karachi

def fetch_data():
    url = f"https://api.openweathermap.org/data/2.5/air_pollution?lat={LAT}&lon={LON}&appid={API_KEY}"
    res = requests.get(url).json()
    # Parse your pollutant/weather data here
    return {
        "temperature_2m": 30,   # Replace with API result
        "relative_humidity_2m": 70,
        "windspeed_10m": 5,
        "winddirection_10m": 180,
        "precipitation": 0,
        "cloudcover": 50,
        "surface_pressure": 1000,
        "co": 50,
        "no": 0.05,
        "no2": 0.1,
        "o3": 40,
        "so2": 0.3,
        "pm2_5": 20,
        "pm10": 50,
        "nh3": 0.1,
        "hour": datetime.utcnow().hour,
        "day": datetime.utcnow().day,
        "month": datetime.utcnow().month,
        "aqi": 2  # If you have it, else leave empty for training targets
    }

def save_features(data):
    df = pd.DataFrame([data])
    os.makedirs("data", exist_ok=True)
    path = "data/features.csv"
    if os.path.exists(path):
        df.to_csv(path, mode='a', header=False, index=False)
    else:
        df.to_csv(path, index=False)
    print(f"Features saved to {path}")

if __name__ == "__main__":
    features = fetch_data()
    save_features(features)