# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gx_y-Y2ogj-RFCaJH4hABqlNhunIyFUN
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import joblib

# Load the feature dataset
df = pd.read_csv("features.csv")

# ✅ Use only features available in Streamlit app
features = [
    'temperature_2m', 'relative_humidity_2m', 'windspeed_10m',
    'winddirection_10m', 'precipitation', 'cloudcover', 'surface_pressure',
    'co', 'no', 'no2', 'o3', 'so2', 'pm2_5', 'pm10', 'nh3',
    'hour', 'day', 'month'
]

X = df[features]
y = df["aqi"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Evaluate
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

train_mse = mean_squared_error(y_train, y_train_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_r2 = r2_score(y_test, y_test_pred)

# Print metrics
print("✅ Training MSE:", train_mse)
print("✅ Training R²:", train_r2)
print("✅ Test MSE:", test_mse)
print("✅ Test R²:", test_r2)

# Save model
joblib.dump(model, "aqi_model.pkl")
print("✅ Model saved as aqi_model.pkl")

